name: Java CI with Maven

on:
  push:
    branches: [ "springboot_3" ]
    paths:
      - '**.java'

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name:  Run the Maven verify phase
      run: mvn --batch-mode verify
